### ISSUE TITLE
TypeError: Cannot read properties of undefined (reading 'baseVal')

### ISSUE THREAD

**Issue by zeitderforschung** [remcohaszing/rehype-mermaidjs#5]
I get an error, when rendering the following mermaidjs diagram with rehype-mermaidjs 2.0.0 that is caused by mermaid-isomorphic 2.1.0. All the other diagrams I have tested work fine.

```
graph LR
A[Confirmed cases] -->|62%| B[Suspected cases]
A -->|15%| C[Diagnosed cases]
A -->|1%| D[Asymptomatic cases]
A -->|2.3%| E[Case-fatality rate]
A -->|3.8%| F[Health care personnel infected]
A -->|81%| G[Mild cases]
A -->|14%| H[Severe cases]
A -->|5%| I[Critical cases]
A -->|80 years: 3%<br>30-79 years: 87%<br>20-29 years: 8%<br>10-19 years: 1%<br><10 years: 1%| J[Age distribution]
A -->|64%| K[Secondary transmission among close contacts]
A -->|The Chinese government has improved its epidemic response capacity since the 2002-2003 SARS outbreak| L[Lessons learned]
```

<img width="915" alt="image" src="https://github.com/remcohaszing/rehype-mermaidjs/assets/54367033/9fc4a21d-2c39-4ec5-8d86-60dfe019e937">

**Comment by remcohaszing** [comment]
Thanks for reporting this. I would like to fix this ASAP, but I'm very busy this week. You can try to fix it yourself of you want.

The issue comes from https://github.com/remcohaszing/mermaid-isomorphic/blob/main/browser.ts#L42

**Comment by zeitderforschung** [comment]
I guess it's related to the DOM Parser that fails on parsing the svg due to missing enclosing tags.
A workaround would be replacing the parser by something like this as you proposed [here](https://github.com/orgs/mermaid-js/discussions/3891):
```js
const wrapper = document.createElement('div')
wrapper.innerHTML = svg
const element = wrapper.firstChild as SVGSVGElement
```
